steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core SDK Version'
    inputs:
      version: 3.0.100-preview7-012821
      packageType: sdk
  - task: DotNetCoreCLI@2
    displayName: Package
    inputs:
      command: pack
      packagesToPack: src/CloudAbstractions.csproj
      configuration: Release
      packDirectory: src/bin/Release/package
      includesymbols: true
      versioningScheme: byBuildNumber
