name: 3.$(Date:yy)$(DayOfYear)$(Rev:.r)
trigger: none
pr:
    autoCancel: true
    branches:
        include:
          - master
stages:
- stage: Build
  displayName: Build Package
  jobs:
  - job: Compile
    displayName: Build Package
    cancelTimeoutInMinutes: 2
    timeoutInMinutes: 15
    pool: Default
    steps:
      - template: build.yml
