name: CI/CD
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build CI/CD
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: '3.0.100'
      - uses: nuget/setup-nuget@v1
      - name: Build Package
        working-directory: ./src
        run: dotnet pack -c Release --include-symbols
      - name: Publish Package
        working-directory: ./src
        run: nuget push ./bin/Release/*.nupkg ${{ secrets.GITHUB_TOKEN }} -source "https://nuget.pkg.github.com/basecap-analytics/index.json"
