name: CI/CD
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build CI/CD
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: '3.1.300'
      - name: Build Package
        working-directory: ./src
        run: dotnet pack -c Release --version-suffix "${GITHUB_RUN_NUMBER}" -p:VersionSuffix=${GITHUB_RUN_NUMBER} --include-symbols
      - name: Publish Package
        working-directory: ./src
        run: dotnet nuget push ./bin/Release/*.nupkg -k ${{ secrets.NuGet_API_Key }} -s "https://www.myget.org/F/bca/api/v2/package"
