name: Pull Request Build
on: pull_request
jobs:
  build:
    name: Build PR
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'
      - name: Build Package
        working-directory: ./src
        run: dotnet pack -c Release /p:RunId=${{github.run_id}} --include-symbols
